### ISSUE TITLE
update_package.bat deleted all my files :(

### ISSUE THREAD

**Issue by hwoitke** [JarodMica/ai-voice-cloning#64]
After clicking on update_package.bat something went wrong and instead of updating, all the files, including the voice models, training data etc. were deleted...

**Comment by JarodMica** [comment]
Hey, sorry to hear about that.  I was just doing some testing and realized that if you run this batch script from outside of the AI Voice Cloning package instead of from inside of it, it would remove the packaged version and everything inside it.  This script should only be ran using the update_package.bat included in the V2 version of the release, instead of downloading from this repository and running from outside of it.

Unfortunately, there is nothing that can be done to get those files back due to the nature of the script, so I have removed those lines in the script that automatically delete the repository here ee3a959e5f867f6733ea507cc896558bab7997ac until I can make the script more robust to your unfortunate case.
