### ISSUE TITLE
Segmentation Fault when generate audio on GCP Server

### ISSUE THREAD

**Issue by zanjabil2502** [JarodMica/ai-voice-cloning#89]
I had problem, every time I run the program and generate audio, the program will always force stop because of a segmentation fault.
![image](https://github.com/JarodMica/ai-voice-cloning/assets/62334332/9176369c-be7c-4f0c-8807-15451d64df71)

**Comment by JarodMica** [comment]
Segmentation fault comes from some type of corruption in maybe the libraries downloaded or the way things were setup, I ran into it once when setting up linux and needed to remove and recreate the virtual environment.  

Try to delete your venv and then start from scratch, though, since your on the cloud, I haven't tried this repo online.

**Comment by zanjabil2502** [comment]
Thanks for the information, but it is solved. I removed torch cuda 11.8 and install torch cuda 12.1.
